create DATABASE PROYECTOGIMNASIO

create TABLE USUARIOS
(
CODIGO INT IDENTITY ,
CORREO VARCHAR(50),
CLAVE VARCHAR (50) NOT NULL,
NOMBRE VARCHAR (50) NOT NULL,
CONSTRAINT PK_CODIGO PRIMARY KEY (CODIGO),
CONSTRAINT UQ_UNIQUE UNIQUE(CORREO)
)

select * from usuarios
INSERT USUARIOS VALUES ('allan@upi.com','123', 'Allan')

create TABLE CLIENTES
(
CODIGO INT identity (1,1),
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR (50) NULL,
TELEFONO VARCHAR (15) NULL,
USUARIO INT,
CONSTRAINT PK_CODIGOCLIENTE PRIMARY KEY (CODIGO),
CONSTRAINT PK_USUARIO1 FOREIGN KEY (USUARIO) REFERENCES  USUARIOS (CODIGO)
)
select * from CLIENTES
INSERT INTO clientes (NOMBRE, APELLIDO, TELEFONO, USUARIO) VALUES ('ALLAN', 'MORALES', '84377956',1)

UPDATE CLIENTES SET NOMBRE = 'ALLAN', APELLIDO ='RAMIREZ', TELEFONO = '33333333'
SELECT * FROM CLIENTES

CREATE TABLE PRODUCTO 
(
CODIGO INT identity ,
NOMBRE VARCHAR(50) NOT NULL,
PRECIO MONEY DEFAULT 0,
CONSTRAINT PK_CODIGOPRODUCTO PRIMARY KEY (CODIGO)
)
UPDATE producto SET NOMBRE = ''
INSERT INTO PRODUCTO VALUES ('BOTELLA AGUA', 500),('CAMISAS', 3000),('COMPUTADORAS', 6000)
SELECT * FROM PRODUCTO

CREATE TABLE PROVINCIA
(
CODIGO INT IDENTITY ,
NOMBRE VARCHAR(50) NOT NULL,
CONSTRAINT PK_CODIGOPROVINCIA PRIMARY KEY (CODIGO)
)
INSERT INTO PROVINCIA VALUES ('SAN JOSE'),('GUANACASTE'),('ALAJUELA'),
('HEREDIA'),('LIMON'),('PUNTARENAS'), ('CARTAGO')
SELECT * FROM PROVINCIA

CREATE TABLE CANTON
(
CODIGO INT IDENTITY ,
NOMBRE VARCHAR(50) NOT NULL,
CODIGO_PROVINCIA INT,
CONSTRAINT PK_CODIGOCANTON PRIMARY KEY (CODIGO),
CONSTRAINT FK_CODIGOPROVINCIA FOREIGN KEY (CODIGO_PROVINCIA) REFERENCES PROVINCIA(CODIGO)
)
INSERT INTO CANTON ( NOMBRE, CODIGO_PROVINCIA) VALUES ( 'CANTON 1', 1), ('CANTON 2',2), ('CANTON 3',1)
 select * from canton

CREATE TABLE DISTRITO
(
CODIGO INT IDENTITY ,
NOMBRE VARCHAR(50) NOT NULL,
CODIGO_CANTON INT,
CONSTRAINT PK_CODIGODISTRITO PRIMARY KEY (CODIGO),
CONSTRAINT FK_CODIGOCANTON FOREIGN KEY (CODIGO_CANTON) REFERENCES CANTON(CODIGO)
)
INSERT INTO Distrito (NOMBRE, CODIGO_CANTON) values ('distrito 1',1), ('DISTRITO 2',1),('DISTRITO 3',1)
select * from distrito

CREATE TABLE DIRECCIONES
(
CODIGO INT IDENTITY ,
CODIGO_CLIENTE INT,
CODIGO_PROVINCIA INT,
CODIGO_CANTON INT,
CODIGO_DISTRITO INT,
CONSTRAINT PK_CODIGODIRECCIONES PRIMARY KEY (CODIGO),
CONSTRAINT FK_CODIGOCLIENTES FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTES(CODIGO),
CONSTRAINT FK_CODIGOPROVINCIA1 FOREIGN KEY (CODIGO_PROVINCIA) REFERENCES PROVINCIA(CODIGO),
CONSTRAINT FK_CODIGOCANTON1 FOREIGN KEY (CODIGO_CANTON) REFERENCES CANTON(CODIGO),
CONSTRAINT FK_CODIGODISTRITO FOREIGN KEY (CODIGO_DISTRITO) REFERENCES DISTRITO(CODIGO)
)
INSERT INTO DIRECCIONES (CODIGO_CLIENTE, CODIGO_PROVINCIA,CODIGO_CANTON,CODIGO_DISTRITO) VALUES (1,1,1,1)
SELECT * FROM DIRECCIONES

CREATE TABLE MAE_FACTURA
(
NFACTURA INT IDENTITY ,
FECHA DATETIME,
CODIGO_CLIENTE INT,
TOTAL MONEY,
CONSTRAINT PK_NFACTURA PRIMARY KEY (NFACTURA),
CONSTRAINT FK_CODIGOCLIENTE2 FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTES(CODIGO)
)

CREATE TABLE DET_FACTURA
(
CODIGO INT IDENTITY ,
NFACTURA INT,
CODIGO_PRODUCTO INT,
CANTIDAD INT,
PRECIO MONEY,
CONSTRAINT PK_CODIGODETFACTURA PRIMARY KEY (CODIGO),
CONSTRAINT FK_NFACTURA FOREIGN KEY (NFACTURA) REFERENCES MAE_FACTURA(NFACTURA),
CONSTRAINT FK_CODIGOPRODUCTO1 FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES PRODUCTO (CODIGO)
)
